name: create pull request to develop

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hotfix'
    steps:
      - name: swich branch and create pull request
      - uses: actions/checkout@v2
        run: |
          git switch master
          gh pr create -t 'リリース差分取り込み master --> develop' -b '差分取り込み用PRです' -l 'release' -B 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
