name: create pull request to develop

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'hotfi')
    steps:
      - uses: actions/checkout@v2
      - name: create pull request
        run: |
          git switch master
          gh pr create -t 'リリース差分取り込み master --> develop' -b '差分取り込み用ブランチです' -l 'release' -B 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
