name: create pull request to develop

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    if: github.head_ref == 'hotfix'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: swich branch and create pull request
        run: |
          git switch master
          gh pr create -t 'リリース差分取り込み master --> develop' \
                      -b '差分取り込み用PRです' \
                      -l 'release' \
                      -B 'develop' \
                      -r miketa-webprgr,DaichiSaito
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
